[common]
tmp_dirpath = 'tmp'
var_dirpath = 'tmp'
log_dirpath = 'tmp'
db_filename = 'fileinfo.sqlite3'
destination_dir = '.old'
datetime_format = '_%Y-%m-%d'
use_seq_num = true
seq_num_sep = '_'
scan_symlink_dir = false
discard_old_backup = true
discard_phase1_weeks = 2
discard_phase2_months = 2
